services:

  dispatcher:
    build:
      context: .
      dockerfile: dispatcher/Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - RABBITMQ_REQUEST_TO_EXCHANGE_QUEUE=${RABBITMQ_REQUEST_TO_EXCHANGE_QUEUE}
      - RABBITMQ_RESPONSE_FROM_EXCHANGE_QUEUE=${RABBITMQ_RESPONSE_FROM_EXCHANGE_QUEUE}

  exchange_proxy:
    build:
      context: .
      dockerfile: exchange_proxy/Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_REQUEST_TO_EXCHANGE_QUEUE=${RABBITMQ_REQUEST_TO_EXCHANGE_QUEUE}
      - RABBITMQ_RESPONSE_FROM_EXCHANGE_QUEUE=${RABBITMQ_RESPONSE_FROM_EXCHANGE_QUEUE}

  rabbitmq:
    image: ${RABBITMQ_IMAGE}
    container_name: ${RABBITMQ_CONTAINER_NAME}
    hostname: ${RABBITMQ_HOSTNAME}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_HTTP_PORT}
      - ${RABBITMQ_AMQP_PORT}
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq/mnesia
    env_file:
      - .env