spring:
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME}
    port:
      - ${RABBITMQ_AMQP_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      exchange: ${RABBITMQ_EXCHANGE_NAME}
      routing-key:
        coin_price_request_key: ${RABBITMQ_COIN_PRICE_REQUEST_ROUTING_KEY}
        coin_price_response_key: ${RABBITMQ_COIN_PRICE_RESPONSE_ROUTING_KEY}
    queues:
      request_to_exchange_queue: ${RABBITMQ_REQUEST_TO_EXCHANGE_QUEUE}
      response_from_exchange_queue: ${RABBITMQ_RESPONSE_FROM_EXCHANGE_QUEUE}

menu:
  pages:
    - exchange_rate: ${MENU_PAGE_EXCHANGE_RATE}
    - alerts: ${MENU_PAGE_ALERTS}
    - add_coin: ${MENU_PAGE_ADD_COIN}
    - settings: ${MENU_PAGE_SETTINGS}
    - main: ${MENU_PAGE_MAIN}

  actions:
    back: ${MENU_ACTION_BACK}

coin:
  prefix: ${COIN_PREFIX}

bot:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}