spring:
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME}
    port:
      - ${RABBITMQ_AMQP_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      exchange: ${RABBITMQ_EXCHANGE_NAME}
      routing-key:
        upsert_user_request: ${RABBITMQ_UPSERT_USER_REQUEST_ROUTING_KEY}
        upsert_user_response: ${RABBITMQ_UPSERT_USER_RESPONSE_ROUTING_KEY}

        delete_favorite_coin_request: ${RABBITMQ_DELETE_FAVORITE_COIN_REQUEST_ROUTING_KEY}
        delete_favorite_coin_response: ${RABBITMQ_DELETE_FAVORITE_COIN_RESPONSE_ROUTING_KEY}

        coin_price_request: ${RABBITMQ_COIN_PRICE_REQUEST_ROUTING_KEY}
        coin_price_response: ${RABBITMQ_COIN_PRICE_RESPONSE_ROUTING_KEY}

        check_coin_exists_request: ${RABBITMQ_CHECK_COIN_EXISTS_REQUEST_ROUTING_KEY}
        check_coin_exists_response: ${RABBITMQ_CHECK_COIN_EXISTS_RESPONSE_ROUTING_KEY}

        add_coin_request: ${RABBITMQ_ADD_COIN_REQUEST_ROUTING_KEY}
        add_coin_response: ${RABBITMQ_ADD_COIN_RESPONSE_ROUTING_KEY}

        change_language_request: ${RABBITMQ_CHANGE_LANGUAGE_REQUEST_ROUTING_KEY}
        change_language_response: ${RABBITMQ_CHANGE_LANGUAGE_RESPONSE_ROUTING_KEY}

        create_notification_request: ${RABBITMQ_CREATE_NOTIFICATION_REQUEST_ROUTING_KEY}
        create_notification_response: ${RABBITMQ_CREATE_NOTIFICATION_RESPONSE_ROUTING_KEY}

        delete_notification_request: ${RABBITMQ_DELETE_NOTIFICATION_REQUEST_ROUTING_KEY}
        delete_notification_response: ${RABBITMQ_DELETE_NOTIFICATION_RESPONSE_ROUTING_KEY}

        service_exception: ${RABBITMQ_SERVICE_EXCEPTION_ROUTING_KEY}
    queues:
      upsert_user_request: ${RABBITMQ_UPSERT_USER_REQUEST_QUEUE}
      upsert_user_response: ${RABBITMQ_UPSERT_USER_RESPONSE_QUEUE}

      delete_favorite_coin_request: ${RABBITMQ_DELETE_FAVORITE_COIN_REQUEST_QUEUE}
      delete_favorite_coin_response: ${RABBITMQ_DELETE_FAVORITE_COIN_RESPONSE_QUEUE}

      coin_price_request: ${RABBITMQ_COIN_PRICE_REQUEST_QUEUE}
      coin_price_response: ${RABBITMQ_COIN_PRICE_RESPONSE_QUEUE}

      check_coin_exists_request: ${RABBITMQ_CHECK_COIN_EXISTS_REQUEST_QUEUE}
      check_coin_exists_response: ${RABBITMQ_CHECK_COIN_EXISTS_RESPONSE_QUEUE}

      add_coin_request: ${RABBITMQ_ADD_COIN_REQUEST_QUEUE}
      add_coin_response: ${RABBITMQ_ADD_COIN_RESPONSE_QUEUE}

      change_language_request: ${RABBITMQ_CHANGE_LANGUAGE_REQUEST_QUEUE}
      change_language_response: ${RABBITMQ_CHANGE_LANGUAGE_RESPONSE_QUEUE}

      create_notification_request: ${RABBITMQ_CREATE_NOTIFICATION_REQUEST_QUEUE}
      create_notification_response: ${RABBITMQ_CREATE_NOTIFICATION_RESPONSE_QUEUE}

      delete_notification_request: ${RABBITMQ_DELETE_NOTIFICATION_REQUEST_QUEUE}
      delete_notification_response: ${RABBITMQ_DELETE_NOTIFICATION_RESPONSE_QUEUE}

      service_exception: ${RABBITMQ_SERVICE_EXCEPTION_QUEUE}

menu:
  action:
    prefix: action_
    back: ${menu.action.prefix}back
    display_edit_coin_sections_menu: ${menu.action.prefix}open_display_coin_sections_menu
    delete_coins: ${menu.action.prefix}delete_coins
    add_coin: ${menu.action.prefix}add_coin
    delete_selected: ${menu.action.prefix}delete_selected
    noop_prefix: noop_
    create_one_time_notification: ${menu.action.prefix}create_one_time_notification
    create_recurring_notification: ${menu.action.prefix}create_recurring_notification

  main:
    name: main_menu
    title:
      ru: "Привет! 👋 Я — бот, который поможет тебе отслеживать изменения курсов криптовалют. 📈💰\n\nДля более удобного взаимодействия со мной ты можешь использовать это меню. 👇"
      en: "Hi! 👋 I'm a bot to help you track cryptocurrency rates. 📈💰\n\nUse the menu below to interact with me more easily. 👇"
    sections:
      ru: "${menu.sections_config.main.ru}"
      en: "${menu.sections_config.main.en}"
    max_buttons_per_row: 2

  coin_selection:
    name: "${menu.action.prefix}selection_menu"
    title:
      ru: "Здесь ты можешь выбрать монету для просмотра подробной информации о ней.\n\nЕсли хочешь изменить список доступных монет, нажми кнопку <b>Редактировать монеты</b> 🛠️."
      en: "Here you can choose a coin to view more details.\n\nTo change the list of available coins, tap <b>Edit Coins</b> 🛠️."
    sections:
      ru: "${menu.sections_config.coin_selection.ru}"
      en: "${menu.sections_config.coin_selection.en}"
    prefix:
      coin: coin_
      currency: -USD
    max_buttons_per_row: 3
    answer_message:
      ru: "Вы выбрали монету 🪙"
      en: "You selected a coin 🪙"

  edit_coin_sections:
    name: edit_coin_sections_menu
    title:
      ru: "Здесь ты можешь управлять своим списком монет: добавлять новые или удалять существующие.\n\nЧтобы добавить монету, просто нажми кнопку <b>Добавить</b> ✨ и следуй инструкциям.\n\nЕсли хочешь удалить одну или несколько монет, нажми кнопку <b>Удалить</b> ❌ и следуй подсказкам, чтобы завершить действие."
      en: "Here you can manage your coin list: add or remove coins.\n\nTo add a coin, tap <b>Add</b> ✨ and follow the instructions.\n\nTo remove coins, tap <b>Delete</b> ❌ and follow the prompts."
    sections:
      ru: "${menu.sections_config.edit_coin_sections.ru}"
      en: "${menu.sections_config.edit_coin_sections.en}"
    max_buttons_per_row: 2

  coin_deletion_menu:
    name: coin_deletion_menu
    title:
      ru: "Здесь ты можешь удалить монеты из своего списка. Чтобы выбрать монету для удаления, просто нажми на неё — появится галочка ✅.\n\nКогда выберешь все монеты, которые хочешь удалить, нажми <b>Удалить выбранные</b>, чтобы подтвердить действие."
      en: "Here you can remove coins from your list. To select a coin for deletion, just tap on it — a checkmark ✅ will appear.\n\nOnce you've selected all the coins you want to delete, tap <b>Delete Selected</b> to confirm."
    sections:
      ru: "${menu.sections_config.coin_deletion.ru}"
      en: "${menu.sections_config.coin_deletion.en}"
    hint:
      ru: "Ты не выбрал ни одной монеты для удаления. 🤔 Чтобы удалить монеты, нажми на них — появится галочка ✅, затем нажми кнопку <b>Удалить выбранные</b>."
      en: "You haven’t selected any coins for deletion. 🤔 Tap on coins to mark them ✅, then tap <b>Delete Selected</b>."
    max_buttons_per_row: 3
    prefix:
      unselected_coin_prefix: unselected_deletion_
      selected_coin_prefix: selected_deletion_

  coin_addition:
    name: adding_new_coin_menu
    title:
      ru: "⚠️ Чтобы добавить новую монету в список отслеживания, введите её название с помощью команды /add (например, BTC, LINK).\n\nТекущий список отслеживаемых монет отображён ниже. 👇"
      en: "⚠️ To add a new coin to your watchlist, enter its name using the /add command (e.g., BTC, LINK).\n\nThe current list of tracked coins is shown below. 👇"
    sections:
      ru: "${menu.sections_config.coin_addition.ru}"
      en: "${menu.sections_config.coin_addition.en}"
    max_buttons_per_row: 3
    answer_messages:
      success:
        ru: "🔎 Отправлен запрос на проверку следующих монет: "
        en: "🔎 Sent a request to check the following coins: "
        msg_type: "_success"
      error:
        ru: "⚠ Вы не указали ни одной криптовалюты\nПример: /add BTC ETH"
        en: "⚠ You didn't specify any coins\nExample: /add BTC ETH"
        msg_type: "_error"
      all_coins_added:
        ru: "✅ Все указанные монеты были успешно добавлены:\n"
        en: "✅ All specified coins were successfully added:\n"
        msg_type: "_all_coins_added"
      some_coins_added:
        ru: "⚠ Некоторые монеты были добавлены, но часть не найдена\n\nДобавлены: {validCoins}\nНе найдены: {invalidCoins}"
        en: "⚠ Some coins were added, but some were not found\n\nAdded: {validCoins}\nNot Found: {invalidCoins}"
        msg_type: "_some_coins_added"
      no_coins_added:
        ru: "❌ Ни одна из указанных монет не была найдена на бирже!"
        en: "❌ None of the specified coins were found on the exchange!"
        msg_type: "_no_coins_added"
    prefix:
      unselected_coin_prefix: unselected_addition_
      selected_coin_prefix: selected_addition_

  price_snapshot:
    name: price_snapshot_menu
    title:
      ru: "⚠️ Чтобы посмотреть определённые данные по монете <b>%s</b>, нажми на соответствующую кнопку ниже. 👇"
      en: "⚠️ To view specific data for the coin <b>%s</b>, tap the corresponding button below. 👇"
    sections:
      ru: "${menu.sections_config.price_snapshot.ru}"
      en: "${menu.sections_config.price_snapshot.en}"
    max_buttons_per_row: 3
    parameters:
      prefix: "${menu.action.prefix}price_snapshot_"
      last_price:
        name: last_price
        description:
          ru: "Текущая цена"
          en: "Current Price"
      highest_price_24h:
        name: highest_price_24h
        description:
          ru: "Максимальная цена за последние 24 часа"
          en: "Highest price in the last 24 hours"
      lowest_price_24h:
        name: lowest_price_24h
        description:
          ru: "Минимальная цена за последние 24 часа"
          en: "Lowest price in the last 24 hours"
      trading_volume:
        name: trading_volume
        description:
          ru: "Общий объём торгов за последние 24 часа"
          en: "Total trading volume in the last 24 hours"
      trading_volume_currency:
        name: trading_volume_currency
        description:
          ru: "Общий объём торгов в валюте за последние 24 часа"
          en: "Total trading volume in currency over the last 24 hours"

  notification:
    name: "${menu.action.prefix}notification_menu"
    title:
      ru: "Ваши уведомления:"
      en: "Your notifications:"
    sections:
      ru: "${menu.sections_config.notification.ru}"
      en: "${menu.sections_config.notification.en}"
    max_buttons_per_row: 2

  notification_creation:
    name: "${menu.action.prefix}creation_notification_menu"
    title:
      ru: "🔔 Выберите тип оповещения!\n\n• 🔂 Однократное — срабатывает один раз при достижении заданного уровня.\n\n• 🔁 Повторяемое — реагирует каждый раз, когда цена пересекает вашу отметку."
      en: "🔔 Choose the type of notification!\n\n• 🔂 One-time — triggers once when the set level is reached.\n\n• 🔁 Recurring — triggered every time the price crosses your specified level."
    sections:
      ru: "${menu.sections_config.notification_creation.ru}"
      en: "${menu.sections_config.notification_creation.en}"
    max_buttons_per_row: 2

  notification_deletion:
    name: "${menu.action.prefix}deletion_notification_menu"
    title:
      ru: "🗑 Удаление оповещения\n\nНажмите на оповещение, которое хотите удалить — оно исчезнет сразу же."
      en: "🗑 Delete Notification\n\nTap the alert you want to remove — it will be deleted instantly."
    sections:
      ru: "${menu.sections_config.notification_deletion.ru}"
      en: "${menu.sections_config.notification_deletion.en}"
    max_buttons_per_row: 2

  settings:
    name: "${menu.action.prefix}settings_menu"
    title:
      ru: "Ваши настройки:"
      en: "Your settings:"
    sections:
      ru: "${menu.sections_config.settings_menu.ru}"
      en: "${menu.sections_config.settings_menu.en}"
    max_buttons_per_row: 1

  language_change:
    name: "${menu.action.prefix}language_change_menu"
    title:
      ru: "Выбранный язык: 🇷🇺 RU"
      en: "Selected language: 🇺🇸 EN"
    sections:
      ru: "${menu.sections_config.language_change.ru}"
      en: "${menu.sections_config.language_change.en}"
    max_buttons_per_row: 2
    prefix: "${menu.action.prefix}change_language_"

  sections_config:
    main:
      ru: "${menu.coin_selection.name}:🪙 Монеты,${menu.notification.name}:🔔 Оповещения,${menu.settings.name}:⚙ Настройки"
      en: "${menu.coin_selection.name}:🪙 Coins,${menu.notification.name}:🔔 Alerts,${menu.settings.name}:⚙ Settings"
    coin_selection:
      ru: "${menu.action.display_edit_coin_sections_menu}:🛠️ Редактировать монеты,${menu.action.back}:↩️ Назад"
      en: "${menu.action.display_edit_coin_sections_menu}:🛠️ Edit Coins,${menu.action.back}:↩️ Back"

    price_snapshot:
      ru: "${menu.price_snapshot.parameters.prefix}${menu.price_snapshot.parameters.last_price.name}:Текущая цена,${menu.price_snapshot.parameters.prefix}${menu.price_snapshot.parameters.highest_price_24h.name}:Макс. цена,${menu.price_snapshot.parameters.prefix}${menu.price_snapshot.parameters.lowest_price_24h.name}:Мин. цена,${menu.price_snapshot.parameters.prefix}${menu.price_snapshot.parameters.trading_volume.name}:Объём торгов,${menu.price_snapshot.parameters.prefix}${menu.price_snapshot.parameters.trading_volume_currency.name}:Объём торгов в валюте,${menu.action.back}:↩️ Назад"
      en: "${menu.price_snapshot.parameters.prefix}${menu.price_snapshot.parameters.last_price.name}:Current Price,${menu.price_snapshot.parameters.prefix}${menu.price_snapshot.parameters.highest_price_24h.name}:Highest price,${menu.price_snapshot.parameters.prefix}${menu.price_snapshot.parameters.lowest_price_24h.name}:Lowest price,${menu.price_snapshot.parameters.prefix}${menu.price_snapshot.parameters.trading_volume.name}:Trading volume,${menu.price_snapshot.parameters.prefix}${menu.price_snapshot.parameters.trading_volume_currency.name}:Trading volume in currency,${menu.action.back}:↩️ Back"

    edit_coin_sections:
      ru: "${menu.action.add_coin}:Добавить,${menu.action.delete_coins}:Удалить,${menu.action.back}:↩️ Назад"
      en: "${menu.action.add_coin}:Add,${menu.action.delete_coins}:Delete,${menu.action.back}:↩️ Back"

    coin_deletion:
      ru: "${menu.action.delete_selected}:Удалить выбранные,${menu.action.back}:↩️ Назад"
      en: "${menu.action.delete_selected}:Delete Selected,${menu.action.back}:↩️ Back"

    coin_addition:
      ru: "${menu.action.back}:↩️ Назад"
      en: "${menu.action.back}:↩️ Back"

    settings_menu:
      ru: "${menu.language_change.name}:Язык — 🇷🇺 RU,${menu.action.back}:↩️ Назад"
      en: "${menu.language_change.name}:Language — 🇺🇸 EN,${menu.action.back}:↩️ Back"

    language_change:
      ru: "${menu.language_change.prefix}ru:RU 🇷🇺,${menu.language_change.prefix}en:EN 🇺🇸,${menu.action.back}:↩️ Назад"
      en: "${menu.language_change.prefix}ru:RU 🇷🇺,${menu.language_change.prefix}en:EN 🇺🇸,${menu.action.back}:↩️ Back"

    notification:
      ru: "${menu.notification_creation.name}:Создать,${menu.notification_deletion.name}:Удалить,${menu.action.back}:↩️ Назад"
      en: "${menu.notification_creation.name}:Add,${menu.notification_deletion.name}:Delete,${menu.action.back}:↩️ Back"

    notification_creation:
      ru: "${menu.action.create_one_time_notification}:Однократное,${menu.action.create_recurring_notification}:Повторяемое,${menu.action.back}:↩️ Назад"
      en: "${menu.action.create_one_time_notification}:One-time,${menu.action.create_recurring_notification}:Recurring,${menu.action.back}:↩️ Back"

    notification_deletion:
      ru: "${menu.action.back}:↩️ Назад"
      en: "${menu.action.back}:↩️ Back"

  answer_message:
    service_exception: ${ANSWER_LOG_MESSAGE_ON_SERVICE_EXCEPTION}

bot:
  token: ${TELEGRAM_BOT_TOKEN}
  command:
    display_main_menu: "/menu"
    display_settings_menu: "/settings"
    display_notification_menu: "/not"
    help: "/help"
    add_coin: "/add"

api:
  exchange:
    url:
      base: ${BASE_API_EXCHANGE_URL}
      market:
        base: ${MARKET_API_EXCHANGE_URL}
        ticker:
          base: ${MARKET_TICKER_API_EXCHANGE_URL}
          response_parameter:
            coin: ${MARKET_TICKER_COIN_RESPONSE_PARAMETER}
            last_price: ${MARKET_TICKER_LAST_PRICE_RESPONSE_PARAMETER}

emoji_unicode_symbol:
  coin: ${COIN_UNICODE_SYMBOL}
  ballot_box_with_check: ${BALLOT_BOX_WITH_CHECK_UNICODE_SYMBOL}
  white_heavy_check_mark: ${WHITE_HEAVY_CHECK_MARK_UNICODE_SYMBOL}