spring:
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME}
    port:
      - ${RABBITMQ_AMQP_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      exchange: ${RABBITMQ_EXCHANGE_NAME}
      routing-key:
        upsert_user_request: ${RABBITMQ_UPSERT_USER_REQUEST_ROUTING_KEY}
        upsert_user_response: ${RABBITMQ_UPSERT_USER_RESPONSE_ROUTING_KEY}

        delete_favorite_coin_request: ${RABBITMQ_DELETE_FAVORITE_COIN_REQUEST_ROUTING_KEY}
        delete_favorite_coin_response: ${RABBITMQ_DELETE_FAVORITE_COIN_RESPONSE_ROUTING_KEY}

        coin_price_request: ${RABBITMQ_COIN_PRICE_REQUEST_ROUTING_KEY}
        coin_price_response: ${RABBITMQ_COIN_PRICE_RESPONSE_ROUTING_KEY}

        check_coin_exists_request: ${RABBITMQ_CHECK_COIN_EXISTS_REQUEST_ROUTING_KEY}
        check_coin_exists_response: ${RABBITMQ_CHECK_COIN_EXISTS_RESPONSE_ROUTING_KEY}

        add_coin_request: ${RABBITMQ_ADD_COIN_REQUEST_ROUTING_KEY}
        add_coin_response: ${RABBITMQ_ADD_COIN_RESPONSE_ROUTING_KEY}

        service_exception: ${RABBITMQ_SERVICE_EXCEPTION_ROUTING_KEY}
    queues:
      upsert_user_request: ${RABBITMQ_UPSERT_USER_REQUEST_QUEUE}
      upsert_user_response: ${RABBITMQ_UPSERT_USER_RESPONSE_QUEUE}

      delete_favorite_coin_request: ${RABBITMQ_DELETE_FAVORITE_COIN_REQUEST_QUEUE}
      delete_favorite_coin_response: ${RABBITMQ_DELETE_FAVORITE_COIN_RESPONSE_QUEUE}

      coin_price_request: ${RABBITMQ_COIN_PRICE_REQUEST_QUEUE}
      coin_price_response: ${RABBITMQ_COIN_PRICE_RESPONSE_QUEUE}

      check_coin_exists_request: ${RABBITMQ_CHECK_COIN_EXISTS_REQUEST_QUEUE}
      check_coin_exists_response: ${RABBITMQ_CHECK_COIN_EXISTS_RESPONSE_QUEUE}

      add_coin_request: ${RABBITMQ_ADD_COIN_REQUEST_QUEUE}
      add_coin_response: ${RABBITMQ_ADD_COIN_RESPONSE_QUEUE}

      service_exception: ${RABBITMQ_SERVICE_EXCEPTION_QUEUE}

menu:
  action:
      prefix: ${ACTION_PREFIX}
      back: ${MENU_ACTION_BACK}
      display_edit_coin_sections_menu: ${MENU_ACTION_DISPLAY_EDIT_COIN_SECTIONS_MENU}
      display_coin_deletion_menu: ${MENU_ACTION_DELETE_COINS}
      delete_selected: ${MENU_ACTION_DELETE_SELECTED}
      display_coin_addition_menu: ${MENU_ACTION_ADD_COINS}
      noop_prefix: ${NOOP_PREFIX}

  main:
      name: ${MENU_MAIN}
      title: ${MENU_TITLE_MAIN}
      sections: ${MENU_SECTIONS_CONFIG_MAIN_MENU}
      max_buttons_per_row: ${MENU_MAX_BUTTONS_PER_ROW_MAIN}

  coin_selection:
    name: ${MENU_COIN_SELECTION}
    title: ${MENU_TITLE_COIN_SELECTION}
    sections: ${MENU_SECTIONS_CONFIG_COIN_SELECTION}
    prefix:
      - coin: ${COIN_PREFIX}
      - currency: ${CURRENCY_PREFIX}
    max_buttons_per_row: ${MENU_MAX_BUTTONS_PER_ROW_COIN_SELECTION}
    answer_message: ${MENU_COIN_SELECTIONS_ANSWER_MESSAGE}

  edit_coin_sections:
    name: ${MENU_EDIT_COIN_SECTIONS}
    title: ${MENU_TITLE_EDIT_COIN_SECTIONS}
    sections: ${MENU_SECTIONS_CONFIG_EDIT_COIN_SECTIONS}
    max_buttons_per_row: ${MENU_MAX_BUTTONS_PER_ROW_EDIT_COIN_SECTIONS}

  coin_deletion_menu:
    name: ${MENU_COIN_DELETION}
    title: ${MENU_TITLE_COIN_DELETION}
    sections: ${MENU_SECTIONS_CONFIG_COIN_DELETION}
    hint: ${MENU_HINT_NO_COINS_SELECTED}
    max_buttons_per_row: ${MENU_MAX_BUTTONS_PER_ROW_COIN_SELECTION}
    prefix:
      unselected_coin_prefix: ${UNSELECTED_DELETION_COIN_PREFIX}
      selected_coin_prefix: ${SELECTED_DELETION_COIN_PREFIX}

  coin_addition:
    name: ${MENU_COIN_ADDITION}
    title: ${MENU_TITLE_COIN_ADDITION}
    sections: ${MENU_SECTIONS_CONFIG_COIN_ADDITION}
    max_buttons_per_row: ${MENU_MAX_BUTTONS_PER_ROW_ADDITION}
    prefix:
      unselected_coin_prefix: ${UNSELECTED_ADDITION_COIN_PREFIX}
      selected_coin_prefix: ${SELECTED_ADDITION_COIN_PREFIX}
    messages:
      success: ${COINS_VALIDATION_REQUESTED}
      error: ${NO_COINS_PROVIDED}
      all_coins_added: ${MSG_ALL_COINS_ADDED}
      some_coins_added: ${MSG_SOME_COINS_ADDED}
      no_coins_added: ${MSG_NO_COINS_ADDED}

  settings:
    name: ${MENU_SETTINGS}

  price_snapshot:
    name: ${MENU_PRICE_SNAPSHOT}
    title: ${MENU_TITLE_COIN_PRICE_SNAPSHOT}
    sections: ${MENU_SECTIONS_CONFIG_COIN_PRICE_SNAPSHOT}
    max_buttons_per_row: ${MENU_MAX_BUTTONS_PER_ROW_PRICE_SNAPSHOT}
    parameters:
      prefix: ${PRICE_SNAPSHOT_PARAMETER_PREFIX}
      last_price:
        name: ${LAST_PRICE_SNAPSHOT_PARAMETER}
        description: ${LAST_PRICE_SNAPSHOT_PARAMETER_DESCRIPTION}
      highest_price_24h:
        name: ${HIGHEST_PRICE_24H_SNAPSHOT_PARAMETER}
        description: ${HIGHEST_PRICE_24H_SNAPSHOT_PARAMETER_DESCRIPTION}
      lowest_price_24h:
        name: ${LOWEST_PRICE_24H_SNAPSHOT_PARAMETER}
        description: ${LOWEST_PRICE_24H_SNAPSHOT_PARAMETER_DESCRIPTION}
      trading_volume:
        name: ${TRADING_VOLUME_PRICE_SNAPSHOT_PARAMETER}
        description: ${TRADING_VOLUME_PRICE_SNAPSHOT_PARAMETER_DESCRIPTION}
      trading_volume_currency:
        name: ${TRADING_VOLUME_CURRENCY_PRICE_SNAPSHOT_PARAMETER}
        description: ${TRADING_VOLUME_CURRENCY_PRICE_SNAPSHOT_PARAMETER_DESCRIPTION}

  answer_message:
    service_exception: ${ANSWER_LOG_MESSAGE_ON_SERVICE_EXCEPTION}

bot:
  token: ${TELEGRAM_BOT_TOKEN}
  command:
    display_main_menu: ${DISPLAY_MAIN_MENU_COMMAND}
    add_coin: ${ADD_COIN_COMMAND}

api:
  exchange:
    url:
      base: ${BASE_API_EXCHANGE_URL}
      market:
        base: ${MARKET_API_EXCHANGE_URL}
        ticker:
          base: ${MARKET_TICKER_API_EXCHANGE_URL}
          response_parameter:
            coin: ${MARKET_TICKER_COIN_RESPONSE_PARAMETER}
            last_price: ${MARKET_TICKER_LAST_PRICE_RESPONSE_PARAMETER}

emoji_unicode_symbol:
  coin: ${COIN_UNICODE_SYMBOL}
  ballot_box_with_check: ${BALLOT_BOX_WITH_CHECK_UNICODE_SYMBOL}
  white_heavy_check_mark: ${WHITE_HEAVY_CHECK_MARK_UNICODE_SYMBOL}