spring:
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME}
    port:
      - ${RABBITMQ_AMQP_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      exchange: ${RABBITMQ_EXCHANGE_NAME}
      routing-key:
        coin_price_request: ${RABBITMQ_COIN_PRICE_REQUEST_ROUTING_KEY}
        coin_price_response: ${RABBITMQ_COIN_PRICE_RESPONSE_ROUTING_KEY}
        service_exception: ${RABBITMQ_SERVICE_EXCEPTION_ROUTING_KEY}
    queues:
      request_to_exchange: ${RABBITMQ_REQUEST_TO_EXCHANGE_QUEUE}
      response_from_exchange: ${RABBITMQ_RESPONSE_FROM_EXCHANGE_QUEUE}

menu:
  name:
    - coin_selection: ${MENU_COIN_SELECTION}
    - alerts: ${MENU_ALERTS}
    - add_coin: ${MENU_ADDING_NEW_COIN}
    - settings: ${MENU_SETTINGS}
    - main: ${MENU_MAIN}
    - price_snapshot: ${MENU_PRICE_SNAPSHOT}
  title:
    - coin_selection: ${MENU_TITLE_COIN_SELECTION}
    - main: ${MENU_TITLE_MAIN}
    - coin_price_snapshot: ${MENU_TITLE_COIN_PRICE_SNAPSHOT}
  section:
    - main: ${MENU_SECTIONS_CONFIG_MAIN_MENU}
    - coin_selection: ${MENU_SECTIONS_CONFIG_COIN_SELECTION}
    - coin_price_snapshot: ${MENU_SECTIONS_CONFIG_COIN_PRICE_SNAPSHOT}



  action:
    back: ${MENU_ACTION_BACK}

coin:
  prefix: ${COIN_PREFIX}

bot:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}

api:
  exchange:
    url:
      base: ${BASE_API_EXCHANGE_URL}
      market:
        base: ${MARKET_API_EXCHANGE_URL}
        ticker:
          base: ${MARKET_TICKER_API_EXCHANGE_URL}
          response_parameter:
            coin: ${MARKET_TICKER_COIN_RESPONSE_PARAMETER}
            last_price: ${MARKET_TICKER_LAST_PRICE_RESPONSE_PARAMETER}