spring:
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME}
    port:
      - ${RABBITMQ_AMQP_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      exchange: ${RABBITMQ_EXCHANGE_NAME}
      routing-key:
        coin_price_request: ${RABBITMQ_COIN_PRICE_REQUEST_ROUTING_KEY}
        coin_price_response: ${RABBITMQ_COIN_PRICE_RESPONSE_ROUTING_KEY}
        service_exception: ${RABBITMQ_SERVICE_EXCEPTION_ROUTING_KEY}
        upsert_user_request: ${RABBITMQ_UPSERT_USER_REQUEST_ROUTING_KEY}
        upsert_user_response: ${RABBITMQ_UPSERT_USER_RESPONSE_ROUTING_KEY}
    queues:
      request_to_exchange: ${RABBITMQ_REQUEST_TO_EXCHANGE_QUEUE}
      response_from_exchange: ${RABBITMQ_RESPONSE_FROM_EXCHANGE_QUEUE}
      request_to_database: ${RABBITMQ_REQUEST_TO_DATABASE_QUEUE}
      response_from_database: ${RABBITMQ_RESPONSE_FROM_DATABASE_QUEUE}

menu:
  action:
      back: ${MENU_ACTION_BACK}
      edit_coin_sections: ${MENU_ACTION_EDIT_COIN_SECTIONS}

  main:
      name: ${MENU_MAIN}
      title: ${MENU_TITLE_MAIN}
      sections: ${MENU_SECTIONS_CONFIG_MAIN_MENU}
      max_buttons_per_row: ${MENU_MAX_BUTTONS_PER_ROW_MAIN}

  coin_selection:
    name: ${MENU_COIN_SELECTION}
    title: ${MENU_TITLE_COIN_SELECTION}
    sections: ${MENU_SECTIONS_CONFIG_COIN_SELECTION}
    prefix:
      - coin: ${COIN_PREFIX}
      - currency: ${CURRENCY_PREFIX}
    max_buttons_per_row: ${MENU_MAX_BUTTONS_PER_ROW_COIN_SELECTION}
    answer_message: ${MENU_COIN_SELECTIONS_ANSWER_MESSAGE}

  settings:
    name: ${MENU_SETTINGS}

  price_snapshot:
    name: ${MENU_PRICE_SNAPSHOT}
    title: ${MENU_TITLE_COIN_PRICE_SNAPSHOT}
    sections: ${MENU_SECTIONS_CONFIG_COIN_PRICE_SNAPSHOT}
    max_buttons_per_row: ${MENU_MAX_BUTTONS_PER_ROW_PRICE_SNAPSHOT}
    parameters:
      prefix: ${PRICE_SNAPSHOT_PARAMETER_PREFIX}
      last_price:
        name: ${LAST_PRICE_SNAPSHOT_PARAMETER}
        description: ${LAST_PRICE_SNAPSHOT_PARAMETER_DESCRIPTION}
      highest_price_24h:
        name: ${HIGHEST_PRICE_24H_SNAPSHOT_PARAMETER}
        description: ${HIGHEST_PRICE_24H_SNAPSHOT_PARAMETER_DESCRIPTION}
      lowest_price_24h:
        name: ${LOWEST_PRICE_24H_SNAPSHOT_PARAMETER}
        description: ${LOWEST_PRICE_24H_SNAPSHOT_PARAMETER_DESCRIPTION}
      trading_volume:
        name: ${TRADING_VOLUME_PRICE_SNAPSHOT_PARAMETER}
        description: ${TRADING_VOLUME_PRICE_SNAPSHOT_PARAMETER_DESCRIPTION}
      trading_volume_currency:
        name: ${TRADING_VOLUME_CURRENCY_PRICE_SNAPSHOT_PARAMETER}
        description: ${TRADING_VOLUME_CURRENCY_PRICE_SNAPSHOT_PARAMETER_DESCRIPTION}

bot:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}

api:
  exchange:
    url:
      base: ${BASE_API_EXCHANGE_URL}
      market:
        base: ${MARKET_API_EXCHANGE_URL}
        ticker:
          base: ${MARKET_TICKER_API_EXCHANGE_URL}
          response_parameter:
            coin: ${MARKET_TICKER_COIN_RESPONSE_PARAMETER}
            last_price: ${MARKET_TICKER_LAST_PRICE_RESPONSE_PARAMETER}