spring:
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME}
    port:
      - ${RABBITMQ_AMQP_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      exchange: ${RABBITMQ_EXCHANGE_NAME}
      routing-key:
        upsert_user_request: ${RABBITMQ_UPSERT_USER_REQUEST_ROUTING_KEY}
        upsert_user_response: ${RABBITMQ_UPSERT_USER_RESPONSE_ROUTING_KEY}

        delete_favorite_coin_request: ${RABBITMQ_DELETE_FAVORITE_COIN_REQUEST_ROUTING_KEY}
        delete_favorite_coin_response: ${RABBITMQ_DELETE_FAVORITE_COIN_RESPONSE_ROUTING_KEY}

        coin_price_request: ${RABBITMQ_COIN_PRICE_REQUEST_ROUTING_KEY}
        coin_price_response: ${RABBITMQ_COIN_PRICE_RESPONSE_ROUTING_KEY}

        check_coin_exists_request: ${RABBITMQ_CHECK_COIN_EXISTS_REQUEST_ROUTING_KEY}
        check_coin_exists_response: ${RABBITMQ_CHECK_COIN_EXISTS_RESPONSE_ROUTING_KEY}

        add_coin_request: ${RABBITMQ_ADD_COIN_REQUEST_ROUTING_KEY}
        add_coin_response: ${RABBITMQ_ADD_COIN_RESPONSE_ROUTING_KEY}

        service_exception: ${RABBITMQ_SERVICE_EXCEPTION_ROUTING_KEY}
    queues:
      upsert_user_request: ${RABBITMQ_UPSERT_USER_REQUEST_QUEUE}
      upsert_user_response: ${RABBITMQ_UPSERT_USER_RESPONSE_QUEUE}

      delete_favorite_coin_request: ${RABBITMQ_DELETE_FAVORITE_COIN_REQUEST_QUEUE}
      delete_favorite_coin_response: ${RABBITMQ_DELETE_FAVORITE_COIN_RESPONSE_QUEUE}

      coin_price_request: ${RABBITMQ_COIN_PRICE_REQUEST_QUEUE}
      coin_price_response: ${RABBITMQ_COIN_PRICE_RESPONSE_QUEUE}

      check_coin_exists_request: ${RABBITMQ_CHECK_COIN_EXISTS_REQUEST_QUEUE}
      check_coin_exists_response: ${RABBITMQ_CHECK_COIN_EXISTS_RESPONSE_QUEUE}

      add_coin_request: ${RABBITMQ_ADD_COIN_REQUEST_QUEUE}
      add_coin_response: ${RABBITMQ_ADD_COIN_RESPONSE_QUEUE}

      service_exception: ${RABBITMQ_SERVICE_EXCEPTION_QUEUE}

menu:
  action:
      prefix: ${ACTION_PREFIX}
      back: ${MENU_ACTION_BACK}
      display_edit_coin_sections_menu: ${MENU_ACTION_DISPLAY_EDIT_COIN_SECTIONS_MENU}
      display_coin_deletion_menu: ${MENU_ACTION_DELETE_COINS}
      delete_selected: ${MENU_ACTION_DELETE_SELECTED}
      display_coin_addition_menu: ${MENU_ACTION_ADD_COINS}
      noop_prefix: ${NOOP_PREFIX}

  main:
      name: ${MENU_MAIN}
      title: "Привет! 👋 Я — бот, который поможет тебе отслеживать изменения курсов криптовалют. 📈💰\n\nДля более удобного взаимодействия со мной ты можешь использовать это меню. 👇"
      sections: ${MENU_SECTIONS_CONFIG_MAIN_MENU}
      max_buttons_per_row: 2

  coin_selection:
    name: ${MENU_COIN_SELECTION}
    title: "Здесь ты можешь выбрать монету для просмотра подробной информацию о ней.\n\nЕсли хочешь изменить список доступных монет нажми кнопку <b>Редактировать монеты</b> 🛠️."
    sections: ${MENU_SECTIONS_CONFIG_COIN_SELECTION}
    prefix:
      - coin: ${COIN_PREFIX}
      - currency: ${CURRENCY_PREFIX}
    max_buttons_per_row: 3
    answer_message: "Вы выбрали монету 🪙"

  edit_coin_sections:
    name: ${MENU_EDIT_COIN_SECTIONS}
    title: "Здесь ты можешь управлять своим списком монет: добавлять новые или удалять существующие.\n\nЧтобы добавить монету, просто нажми кнопку <b>Добавить</b> ✨ и следуй инструкциям.\n\nЕсли хочешь удалить одну или несколько монет, нажми кнопку <b>Удалить</b> ❌ и следуй подсказкам, чтобы завершить действие."
    sections: ${MENU_SECTIONS_CONFIG_EDIT_COIN_SECTIONS}
    max_buttons_per_row: 2

  coin_deletion_menu:
    name: ${MENU_COIN_DELETION}
    title: "Здесь ты можешь удалить монеты из своего списка. Чтобы выбрать монету для удаления, просто нажми на неё — появится галочка ✅.\n\nКогда выберешь все монеты, которые хочешь удалить, нажми <b>Удалить выбранные</b>, чтобы подтвердить действие."
    sections: ${MENU_SECTIONS_CONFIG_COIN_DELETION}
    hint: "Ты не выбрал ни одной монеты для удаления. 🤔 Чтобы удалить монеты, нажми на них — появится галочка ✅, затем нажми кнопку <b>Удалить выбранные</b>, чтобы продолжить."
    max_buttons_per_row: 3
    prefix:
      unselected_coin_prefix: ${UNSELECTED_DELETION_COIN_PREFIX}
      selected_coin_prefix: ${SELECTED_DELETION_COIN_PREFIX}

  coin_addition:
    name: ${MENU_COIN_ADDITION}
    title: "⚠️ Чтобы добавить новую монету в список отслеживания, введите её название с помощью команды /add (например, BTC, LINK).\n\nТекущий список отслеживаемых монет отображён ниже. 👇"
    sections: ${MENU_SECTIONS_CONFIG_COIN_ADDITION}
    max_buttons_per_row: 3
    messages:
      success: "🔎 Отправлен запрос на проверку следующих монет: "
      error: "⚠ Вы не указали ни одной криптовалюты\nПример: /add BTC ETH"
      all_coins_added: "✅ Все указанные монеты были успешно добавлены:\n"
      some_coins_added: "Некоторые монеты были добавлены, но часть не найдена ⚠️\n\nДобавлены: {validCoins}\nНе найдены: {invalidCoins}"
      no_coins_added: "❌ Ни одна из указанных монет не была найдена на бирже!"

  settings:
    name: ${MENU_SETTINGS}

  price_snapshot:
    name: ${MENU_PRICE_SNAPSHOT}
    title: "⚠️ Чтобы посмотреть определённые данные по монете <b>%s</b>, нажми на соответствующую кнопку ниже. 👇"
    sections: ${MENU_SECTIONS_CONFIG_COIN_PRICE_SNAPSHOT}
    max_buttons_per_row: 3
    parameters:
      prefix: ${PRICE_SNAPSHOT_PARAMETER_PREFIX}
      last_price:
        name: ${LAST_PRICE_SNAPSHOT_PARAMETER}
        description: "Текущая цена"
      highest_price_24h:
        name: ${HIGHEST_PRICE_24H_SNAPSHOT_PARAMETER}
        description: "Максимальная цена за последние 24 часа"
      lowest_price_24h:
        name: ${LOWEST_PRICE_24H_SNAPSHOT_PARAMETER}
        description: "Минимальная цена за последние 24 часа"
      trading_volume:
        name: ${TRADING_VOLUME_PRICE_SNAPSHOT_PARAMETER}
        description: "Общий объём торгов за последние 24 часа"
      trading_volume_currency:
        name: ${TRADING_VOLUME_CURRENCY_PRICE_SNAPSHOT_PARAMETER}
        description: "Общий объём торгов в валюте за последние 24 часа"

  answer_message:
    service_exception: ${ANSWER_LOG_MESSAGE_ON_SERVICE_EXCEPTION}

bot:
  token: ${TELEGRAM_BOT_TOKEN}
  command:
    display_main_menu: "/menu"
    add_coin: "/add"

api:
  exchange:
    url:
      base: ${BASE_API_EXCHANGE_URL}
      market:
        base: ${MARKET_API_EXCHANGE_URL}
        ticker:
          base: ${MARKET_TICKER_API_EXCHANGE_URL}
          response_parameter:
            coin: ${MARKET_TICKER_COIN_RESPONSE_PARAMETER}
            last_price: ${MARKET_TICKER_LAST_PRICE_RESPONSE_PARAMETER}

emoji_unicode_symbol:
  coin: ${COIN_UNICODE_SYMBOL}
  ballot_box_with_check: ${BALLOT_BOX_WITH_CHECK_UNICODE_SYMBOL}
  white_heavy_check_mark: ${WHITE_HEAVY_CHECK_MARK_UNICODE_SYMBOL}