spring:
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    queues:
      request_queue: ${RABBITMQ_COIN_REQUEST_QUEUE}
      response_queue: ${RABBITMQ_COIN_RESPONSE_QUEUE}
      notification_queue: ${RABBITMQ_NOTIFICATION_QUEUE}
    template:
      exchange: ${RABBITMQ_EXCHANGE_NAME}