spring:
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME}
    port:
      - ${RABBITMQ_AMQP_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      exchange: ${RABBITMQ_EXCHANGE_NAME}
      routing-key:
        coin_price_key: ${RABBITMQ_COIN_PRICE_ROUTING_KEY}
    queues:
      request_to_exchange_queue: ${RABBITMQ_REQUEST_TO_EXCHANGE_QUEUE}
      response_from_exchange_queue: ${RABBITMQ_RESPONSE_FROM_EXCHANGE_QUEUE}
      notification_queue: ${RABBITMQ_NOTIFICATION_QUEUE}

coin:
  prefix: ${COIN_PREFIX}